In [3]:
from transformers import AutoTokenizer
from transformers import AutoModelForCausalLM
import torch

model_name = "Qwen/Qwen2.5-0.5B"
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForCausalLM.from_pretrained(model_name)

model.safetensors:   0%|          | 0.00/988M [00:00<?, ?B/s]

c:\Users\Mahesh.shriram\AppData\Local\Programs\Python\Python313\Lib\site-packages\huggingface_hub\file_download.py:138: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\Mahesh.shriram\.cache\huggingface\hub\models--Qwen--Qwen2.5-0.5B. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)


Loading weights:   0%|          | 0/290 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/138 [00:00<?, ?B/s]

In [4]:
text = "Python is a programming language"
inputs = tokenizer(
    text,
    return_tensors = 'pt'
)
print(inputs)

{'input_ids': tensor([[30280,   374,   264, 15473,  4128]]), 'attention_mask': tensor([[1, 1, 1, 1, 1]])}


In [ ]:
print(inputs["input_ids"].shape)
#batch_size = x, sequence_lenght = y

torch.Size([1, 5])


In [8]:
output = model(**inputs)

In [9]:
print(output.keys())

odict_keys(['logits', 'past_key_values'])


In [ ]:
print(output['logits'].shape)
# x = batch size, y = input tokens, z = vocabulary size

torch.Size([1, 5, 151936])


In [13]:
print(output.logits[0][0])

tensor([ 7.0625,  7.9375,  8.2500,  ..., -4.2812, -4.2812, -4.2812],
       dtype=torch.bfloat16, grad_fn=<SelectBackward0>)


In [15]:
predicted_token = output.logits[0][0].argmax()
print(predicted_token)

tensor(220)


In [20]:
print(
    tokenizer.decode(predicted_token)
)

In [21]:
outputs = model(
    **inputs,
    labels=inputs["input_ids"]
)

In [22]:
print(outputs.loss)

tensor(1.6037, grad_fn=<NllLossBackward0>)


In [24]:
print(inputs["input_ids"])

print(inputs["input_ids"].shape)

print(outputs.logits.shape)

print(outputs.loss)

print(outputs.logits[0][0][:10])

print(outputs.logits[0][0].argmax())

print(f"Decoded: {tokenizer.decode(outputs.logits[0][0].argmax())}")

tensor([[30280,   374,   264, 15473,  4128]])
torch.Size([1, 5])
torch.Size([1, 5, 151936])
tensor(1.6037, grad_fn=<NllLossBackward0>)
tensor([7.0625, 7.9375, 8.2500, 4.9688, 4.9375, 8.6875, 7.7812, 8.6875, 7.6562,
        9.1250], dtype=torch.bfloat16, grad_fn=<SliceBackward0>)
tensor(220)
Decoded:  
